package {
	import custom.utilities.*;
	
	import flexlocator.*;
	
	import flexunit.framework.TestSuite;
	
	import funfx.log.LogTest;
	
	import recording.*;

	/*
		This file is autogenerated by rake test:build:suite. Manual changes to it
		are going to be blown away next time it is generated, so don't edit it if you
		want to keep your changes around.
	*/
	public class FunFxTestSuite extends TestSuite {
		public function FunFxTestSuite(param:Object=null) {
			super(param);
						
			addTests();
		}

		protected function addTests():void {
			// flexlocator			
			addTestSuite(LocatorTest)

			// recording			
			addTestSuite(FunFXRecordingTest)

      // logger
      addTestSuite(LogTest)

			// custom.utilities			
			addTestSuite(CSVUtilityTest)
			addTestSuite(FlexObjectLocatorUtilityTest)

		}
	}
}
