ENV['NODOT'] = 'true' # We don't want diagrams in RDoc - we make our own Dot diagram!
require 'config/requirements'
require 'config/hoe' # setup Hoe + all gem configuration

Dir['rake_tasks/**/*.rake'].each { |rake| load rake }